# Generated by Django 5.0.6 on 2024-08-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
