# Generated by Django 5.0.6 on 2024-08-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilepic',
        ),
    ]
