# Generated by Django 5.0.6 on 2024-08-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='profile',
        ),
        migrations.AddField(
            model_name='book',
            name='buyer',
            field=models.ManyToManyField(related_name='buyer', to='book.profile'),
        ),
    ]
