# Generated by Django 5.0.6 on 2024-09-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number',
        ),
    ]
